@startuml
set separator none
title Note Taker App - Backend API - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System(D1Database, "D1 Database", $descr="Stores users, notes, and sharing.", $tags="", $link="")

Container_Boundary("NoteTakerApp.BackendAPI_boundary", "Backend API", $tags="") {
  Component(NoteTakerApp.BackendAPI.NoteController, "Note Controller", $techn="Hono", $descr="Invokes use cases for notes.", $tags="", $link="")
  Component(NoteTakerApp.BackendAPI.UserController, "User Controller", $techn="Hono", $descr="Invokes use cases for user authentication.", $tags="", $link="")
  Component(NoteTakerApp.BackendAPI.NoteModule, "Note Module", $techn="Clean Architecture", $descr="Implements use cases for note.", $tags="", $link="")
  Component(NoteTakerApp.BackendAPI.UserModule, "User Module", $techn="Clean Architecture", $descr="Implements use cases for user.", $tags="", $link="")
  Component(NoteTakerApp.BackendAPI.DataAccessLayer, "Data Access Layer", $techn="SQL Queries/ ORM /D1 SDK", $descr="Interacts with the D1 database.", $tags="", $link="")
}

Rel(NoteTakerApp.BackendAPI.NoteController, NoteTakerApp.BackendAPI.NoteModule, "Invokes notes's use cases", $techn="", $tags="", $link="")
Rel(NoteTakerApp.BackendAPI.UserController, NoteTakerApp.BackendAPI.UserModule, "Invokes users's use cases", $techn="", $tags="", $link="")
Rel(NoteTakerApp.BackendAPI.NoteModule, NoteTakerApp.BackendAPI.DataAccessLayer, "", $techn="", $tags="", $link="")
Rel(NoteTakerApp.BackendAPI.UserModule, NoteTakerApp.BackendAPI.DataAccessLayer, "", $techn="", $tags="", $link="")
Rel(NoteTakerApp.BackendAPI.DataAccessLayer, D1Database, "Executes queries", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml